import { StyleSheet, Dimensions } from "react-native";

const { width } = Dimensions.get("window");
export const DRAWER_WIDTH = width * 0.75;

export const aiStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#F4F6FB",
  },

  overlay: {
    position: "absolute",
    top: 0, left: 0, right: 0, bottom: 0,
    backgroundColor: "rgba(0,0,0,0.4)",
    zIndex: 10,
  },
  drawer: {
    position: "absolute",
    top: 0, left: 0, bottom: 0,
    width: DRAWER_WIDTH,
    backgroundColor: "#FFFFFF",
    zIndex: 20,
    paddingTop: 56,
    paddingHorizontal: 16,
    shadowColor: "#000",
    shadowOffset: { width: 2, height: 0 },
    shadowOpacity: 0.15,
    shadowRadius: 8,
    elevation: 10,
  },
  drawerTitle: {
    fontSize: 18,
    fontWeight: "700",
    color: "#1C2A4A",
    marginBottom: 20,
  },
  newChatBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    backgroundColor: "#3F5E95",
    borderRadius: 12,
    paddingVertical: 12,
    paddingHorizontal: 16,
    marginBottom: 24,
  },
  newChatText: {
    color: "#FFFFFF",
    fontWeight: "600",
    fontSize: 15,
  },
  drawerSectionTitle: {
    fontSize: 12,
    fontWeight: "600",
    color: "#8B93A7",
    letterSpacing: 0.8,
    marginBottom: 8,
    textTransform: "uppercase",
  },
  conversationItem: {
    paddingVertical: 12,
    paddingHorizontal: 12,
    borderRadius: 10,
    marginBottom: 4,
  },
  conversationItemActive: {
    backgroundColor: "#EEF2FA",
  },
  conversationItemText: {
    fontSize: 14,
    color: "#2D3A52",
    fontWeight: "500",
  },
  conversationItemDate: {
    fontSize: 11,
    color: "#8B93A7",
    marginTop: 2,
  },
  deleteBtn: {
    padding: 6,
    marginLeft: 8,
  },
  conversationRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },

  header: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 16,
    paddingTop: 56,
    paddingBottom: 14,
    backgroundColor: "#FFFFFF",
    borderBottomWidth: 1,
    borderBottomColor: "#E8ECF4",
    gap: 12,
  },
  headerBtn: {
    width: 38,
    height: 38,
    borderRadius: 10,
    backgroundColor: "#F4F6FB",
    alignItems: "center",
    justifyContent: "center",
  },
  headerTitle: {
    fontSize: 17,
    fontWeight: "700",
    color: "#1C2A4A",
  },
  headerSubtitle: {
    fontSize: 12,
    color: "#8B93A7",
  },

  messageBubble: {
    maxWidth: "85%",
    borderRadius: 16,
    paddingVertical: 10,
    paddingHorizontal: 14,
    marginBottom: 10,
  },
  userBubble: {
    backgroundColor: "#3F5E95",
    alignSelf: "flex-end",
    borderBottomRightRadius: 4,
  },
  aiBubble: {
    backgroundColor: "#FFFFFF",
    alignSelf: "flex-start",
    borderBottomLeftRadius: 4,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.06,
    shadowRadius: 4,
    elevation: 2,
  },
  userBubbleText: {
    color: "#FFFFFF",
    fontSize: 15,
    lineHeight: 22,
  },
  aiBubbleText: {
    color: "#2D3A52",
    fontSize: 15,
    lineHeight: 22,
  },
  timestampText: {
    fontSize: 10,
    color: "#8B93A7",
    marginTop: 4,
    alignSelf: "flex-end",
  },

  inlineEventCard: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#F0F4FF",
    borderRadius: 10,
    marginTop: 8,
    padding: 10,
    borderLeftWidth: 3,
    borderLeftColor: "#3F5E95",
    gap: 8,
  },
  inlineEventInfo: {
    flex: 1,
  },
  inlineEventTitle: {
    fontSize: 13,
    fontWeight: "700",
    color: "#1C2A4A",
  },
  inlineEventSub: {
    fontSize: 11,
    color: "#5A6A8A",
    marginTop: 1,
  },
  inlineEventBtn: {
    backgroundColor: "#3F5E95",
    borderRadius: 8,
    paddingVertical: 6,
    paddingHorizontal: 10,
    alignItems: "center",
    justifyContent: "center",
  },
  inlineEventBtnText: {
    color: "#FFFFFF",
    fontSize: 11,
    fontWeight: "700",
  },

  typingDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: "#8B93A7",
    marginHorizontal: 2,
  },
  typingContainer: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 4,
    paddingVertical: 4,
  },

  inputBar: {
    flexDirection: "row",
    alignItems: "flex-end",
    paddingHorizontal: 16,
    paddingVertical: 12,
    backgroundColor: "#FFFFFF",
    borderTopWidth: 1,
    borderTopColor: "#E8ECF4",
    gap: 10,
  },
  input: {
    flex: 1,
    minHeight: 44,
    maxHeight: 120,
    backgroundColor: "#F4F6FB",
    borderRadius: 22,
    paddingHorizontal: 18,
    paddingVertical: 10,
    fontSize: 15,
    color: "#1C2A4A",
  },
  sendBtn: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: "#3F5E95",
    alignItems: "center",
    justifyContent: "center",
  },
  sendBtnDisabled: {
    backgroundColor: "#C5CEDF",
  },

  emptyState: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 32,
    gap: 12,
  },
  emptyIcon: {
    width: 72,
    height: 72,
    borderRadius: 36,
    backgroundColor: "#EEF2FA",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 8,
  },
  emptyTitle: {
    fontSize: 20,
    fontWeight: "700",
    color: "#1C2A4A",
    textAlign: "center",
  },
  emptySubtitle: {
    fontSize: 14,
    color: "#8B93A7",
    textAlign: "center",
    lineHeight: 21,
  },
  suggestionsRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    justifyContent: "center",
    marginTop: 8,
  },
  suggestionChip: {
    backgroundColor: "#FFFFFF",
    borderRadius: 20,
    paddingVertical: 8,
    paddingHorizontal: 14,
    borderWidth: 1,
    borderColor: "#E0E6F0",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 2,
    elevation: 1,
  },
  suggestionChipText: {
    fontSize: 13,
    color: "#3F5E95",
    fontWeight: "500",
  },
joinCard: {
  flexDirection: "row",
  alignItems: "center",
  justifyContent: "space-between",
  backgroundColor: "#F0F4FF",
  borderRadius: 10,
  marginTop: 8,
  padding: 10,
  borderLeftWidth: 3,
  borderLeftColor: "#3F5E95",
},
joinCardInfo: {
  flexDirection: "row",
  alignItems: "center",
  gap: 6,
  flex: 1,
},
joinCardText: {
  fontSize: 13,
  color: "#2D3A52",
},
joinCardBtn: {
  backgroundColor: "#3F5E95",
  borderRadius: 8,
  paddingVertical: 6,
  paddingHorizontal: 14,
  alignItems: "center",
  justifyContent: "center",
  minWidth: 72,
},
joinCardBtnText: {
  color: "#FFFFFF",
  fontSize: 12,
  fontWeight: "700",
},
joinCardDoneText: {
  fontSize: 13,
  color: "#4CAF50",
  fontWeight: "600",
},
});