import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({

  page: { flex: 1, backgroundColor: "#F4F6F9" },
  header: {
    paddingTop: 60,
    paddingBottom: 20,
    paddingHorizontal: 16,
    backgroundColor: "#3F5E95",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  headerTitle: { color: "#fff", fontSize: 20, fontWeight: "800" },
  backBtn: { width: 44, height: 44, justifyContent: "center" },
  rightSpacer: { width: 44 },
  content: { flex: 1, paddingHorizontal: 16, paddingTop: 16 },
  center: { flex: 1, justifyContent: "center", alignItems: "center" },
  unreadLabel: {
    fontSize: 13,
    fontWeight: "700",
    color: "#8B93A7",
    marginBottom: 12,
  },
  listContent: { paddingBottom: 40 },
  card: {
    backgroundColor: "#fff",
    borderRadius: 12,
    padding: 14,
    marginBottom: 10,
    shadowColor: "#000",
    shadowOpacity: 0.04,
    shadowRadius: 8,
    elevation: 1,
    position: "relative",
    overflow: "hidden",
  },
  cardUnread: {
    backgroundColor: "#EEF3FF",
    borderLeftWidth: 3,
    borderLeftColor: "#3F5E95",
  },
  cardRow: { flexDirection: "row", alignItems: "center", gap: 12 },
  iconWrap: {
    width: 36,
    height: 36,
    borderRadius: 10,
    backgroundColor: "#F4F6F9",
    alignItems: "center",
    justifyContent: "center",
  },
  cardBody: { flex: 1 },
  message: { fontSize: 14, color: "#6B7280", lineHeight: 20 },
  messageUnread: { color: "#1E2A3B", fontWeight: "600" },
  time: { fontSize: 12, color: "#8B93A7", marginTop: 4 },
  unreadDot: {
    position: "absolute",
    top: 14,
    right: 14,
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: "#3F5E95",
  },
  errorText: { color: "#DC2626", fontWeight: "600", marginBottom: 12, textAlign: "center" },
  retryBtn: { paddingHorizontal: 20, paddingVertical: 10, backgroundColor: "#3F5E95", borderRadius: 8 },
  retryText: { color: "#fff", fontWeight: "700" },
  emptyTitle: { fontSize: 16, fontWeight: "800", color: "#4A5568", marginBottom: 8 },
  emptySubtitle: { fontSize: 13, color: "#8B93A7", textAlign: "center", paddingHorizontal: 30 },
});
